### ISSUE TITLE
Request: FW .58 Release

### ISSUE THREAD

**Issue by atrac17** [marqs85/DExx-vd_isl#3]
Could you please provide a release for the newest FW with profile saving/loading? I setup up a build env to compile the software image, but it is pointless as I do not have the Intel VIP license.

Also, have you considered adding support for the custom_scaler profiles that can be loaded via .txt? I'd like to try the **[scaler methods](https://github.com/atrac17/Integer_Video_Modes)** I use on MiSTer with this device. If not, profiles will suffice. Thank you for this wonderful project.

**Comment by marqs85** [comment]
Profile saving/loading has been now implemented on OSSC Pro side and I'm currently integrating those changes to DExx. There is some issue with the flash controller (possible due to different vendor's flash chip on DE10-Nano) which I need to resolve before the firmware can be released.

The software image can be built and downloaded on the board without the license. It's just the RTL part which needs the license if you want to compile a bitstream that doesn't require USB Blaster connection while in use.

By scaler methods, do you mean just the polyphase filter coefficients or basically all scaler settings? Support for cofficient loading is planned since that's already available on OSSC Pro. The difference on DE10-Nano is that by default SD card is utilized by HPS side so I'd need to check if it can be properly handed over to FPGA/soft-CPU after bootup. Another way would be evaluating if all the SW could be easily moved on the HPS without making the firmware too DE10-Nano specific (see [TODOs](https://github.com/marqs85/DExx-vd_isl/blob/master/board/de10-nano/README.md)).

**Comment by atrac17** [comment]
I'd like to use my own ini files with custom video modes for HW on the scaler side. Assume this is where "custom _scaler.txt" comes into play.

**Comment by marqs85** [comment]
Sampling presets can be customized and are saved as part of a profile. It's also planned that the output mode parameters (ref. video_modes[]) could be tweaked as they are also included in the profile. A profile import/export feature (i.e. from/to SD card) is a planned feature since it's supported already by OSSC Classic. That should allow definition of custom table of video modes. 

With DExx / OSSC Pro the profile could be encoded/decoded to/from txt format opposed to binary data on Classic which needs some work on a parser etc.

**Comment by atrac17** [comment]
I assume the load/save profile for the DExx is not limited? It's probably best to go this route for arcade hardware. I have about 60 PCB's that I would like to make custom profiles. 

I do "hybrid scaling", it's compatible with the OSSC "classic". The pre-defined Neo Geo mode on the DExx FW would be an example.

If a .txt file could be parsed, how would parameters be defined? I have several listed  **[here](https://github.com/atrac17/Integer_Video_Modes)**.

**Comment by marqs85** [comment]
It seems the on-board flash can be only accessed if the FPGA boots from it (AS mode) which is an annoying Cyclone V limitation. I'll have to next try if loaning SD pins to FPGA side works so that profiles could be saved there while retaining HPS-based boot. SD cards should at least have space for practically infinite amount of profiles.

Regarding parsing, you can see the struct members for a sampling preset [here](https://github.com/marqs85/ossc_pro/blob/2275b124a579b4f84cc87528a749310c679546f6/software/sys_controller/inc/video_modes.h#L216).

**Comment by marqs85** [comment]
25f425dc7346ee215d746c51cfede3ab62e99db0 now implements a framework for saving & loading profiles (up to 100) on SD. However, there is one remaining issue in SD card controller with regards to write which needs to be resolved before the firmware can be released.

**Comment by atrac17** [comment]
Great work, thank you!

**Comment by marqs85** [comment]
There is now a beta [image](http://www.infocult.com/m/tmp/sdcard_cv_058beta2.img.zip) which supports storing profiles on SD. 2 MiSTer filters can be also put on the card as scaler1.txt and scaler2.txt and activated from Scaling Algorithm menu.

**Comment by atrac17** [comment]
Awesome, I'll give it a go here shortly. Thank you very much.

**Comment by jaffa225** [comment]
> There is now a beta [image](http://www.infocult.com/m/tmp/sdcard_cv_058beta2.img.zip) which supports storing profiles on SD. 2 MiSTer filters can be also put on the card as scaler1.txt and scaler2.txt and activated from Scaling Algorithm menu.

My settings are saving and reloading properly (Thanks!), but I didn't test the MISTer filters options yet.  This is a real time-saver for me, and very appreciated! :)

**Comment by atrac17** [comment]
Thanks again @marqs85! Closing this.

**Comment by marqs85** [comment]
The SD card issues should be now properly fixed in c4d6a4a.

**Comment by jaffa225** [comment]
> The SD card issues should be now properly fixed in [c4d6a4a](https://github.com/marqs85/DExx-vd_isl/commit/c4d6a4af24cbbef8543f654cacb34da9c032a3d4).

I hadn't noticed any issue with it, but thank you!  I know what it's like to notice when my own patches need improvement.  I'm happily up-to-date now, and even my previously saved profile & settings were easily copied back to restore on firmware version 0.59.  Compressing it was a great idea, as it's now so easily downloaded!
